export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const CREATE_GRADITUDE = 'CREATE_GRADITUDE'
export const FETCH_GRADITUDES = 'FETCH_GRADITUDES'
export const FETCH_GRADITUDE = 'FETCH_GRADITUDE'
export const DELETE_GRADITUDE = 'DELETE_GRADITUDE'
export const EDIT_GRADITUDE = 'EDIT_GRADITUDE'
//:)
